### ISSUE TITLE
Usar métricas custom para escalamiento de steps

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/kubernetes_pipeline#40]
```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/APF/issues/32
- [x] Update de steps a APF 2.0
- [ ] https://github.com/alercebroker/infrastructure_provisioning/issues/87
```

**Comment by dirodriguezm** [comment]
Closed in #47
